### ISSUE TITLE
the dark trilogy server (1.0.5) crash

### ISSUE THREAD

**Issue by zigmal** [Chicken-Bones/ChickenChunks#17]
Not really sure why this keeps crashing my server , only way i can get the server to start back up is by deleting the logintimers.dat file inside world/chickenchunks.

http://pastebin.com/WYsQPsGG

any help would be awesome :D

**Comment by Bitterholz** [comment]
Ive had the same problem.

Updateing to ChickenChunks_1.3.4.16 AND deleting the /<server>/<world>/chickenchunks folder completely, solved the Problem!
I hope it wont appear again :) Thanks for the great work CB!
